# Lightweight Node image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy backend package files
COPY backend/package*.json ./

# Install dependencies
RUN npm install

# Copy backend source code
COPY backend .

# Expose Express port
EXPOSE 5000

# Start server
CMD ["node", "src/server.js"]
